class AppBanner {
  final int id;
  final String title;
  final String location;
  final String timing;
  final String thumbnail;
  final String description;
  final String entryfee;

  AppBanner(this.id, this.title, this.location, this.timing, this.thumbnail, this.description, this.entryfee);
}

List<AppBanner> beachesList = [
  AppBanner(1, "Versova Beach", "Bharat Nagar, Versova", "24×7", "versovabeach.jpg", "Dry black and white sand lends a unique appeal to this peaceful and clean beach. You can simply laze around, go for a swim, watch or participate in a fish auction (the beach is home to a well-known fishing community, Koli), or dig into some tasty seafood at one of the cafes here. Those seeking thrill can indulge in snorkelling, surfing or scuba diving. Photographers will fall in love with the beach at dawn and dusk.", "Free"),

  AppBanner(2, "Juhu Chowpatty", "Juhu Tara Rd, Juhu", " 24x7", "juhuchowpatty.jpg", "Nothing can be more romantic than watching the crimson sun and the luminous orange sky on a breezy beach, with your loved one. Juhu Beach is one such spectacular place in Mumbai, often visited by couples who need a little romantic escape from the humdrum of city life. You can also plan a romantic date night at one of the amazing beachside restaurants available at Juhu.", "Free"),

  AppBanner(3, "Girgaon Chowpatty", "Girgaon/Churni Rd", "24×7", "girgaonchowpatty.jpg", "Looking for a breezy getaway that doesn’t cost a bomb? This public beach that lies along the Queen’s Necklace is the answer to your prayers. Counted among the best Mumbai tourist places, this beach is famous for grand Ganesh Visarjan celebrations, where countless people flock to witness Lord Ganesha’s immersion. This beach is known for its 10-day Ram Leela performance too, at the end of which, Ravan’s effigy is set afire. Also, if you want to admire the Nariman Point skyline in all its glory, Girgaon Chowpatty is where you should be.", "Free"),

  AppBanner(4, "Aksa Beach", "Aksa Gaon, Madh", "24×7", "aksabeach.jpg", "Located a little on the outskirts of the city in Malad, Aksa Beach is an unparalleled oasis for a rejuvenating retreat from the hustle bustle of the city traffic. The beach, no doubt, owes most of its fame to the song ‘Tujhe Aksa Beach ghuma du’ from the hot shot Bollywood movie but is lately becoming a choicest pick among tourists seeking tranquility and peace from the mainstream chowpattis in Bombay. The mesmerising coastline is one of the longest in the city and offers an extremely vivid and surreal panorama of the merging horizon ahead. The beach is still untouched by the city crowds and hence maintains its natural charm apart from being immaculately clean.", "Free"),

];

List<AppBanner> parksList = [
  AppBanner(1, "Sanjay Gandhi National Park", "Borivali East", "07:30 am to 06:30 pm; closed on Mondays", "sgnp.jpg", "Sprawling over an area of 104 sq. km. of land, this is one of the most-visited national parks in Asia and because of this, I give it the 2nd spot among all the best places to visit in Mumbai. With all sorts of fun activities, this park can surely be a family entertainer. You can watch the big cats of the park close enough in a safari cage and have a fun day boating in the artificial lake in the park. Take the forest road or stairs and hike towards the Gandhi Tekdi, a memorial built in the memory of Mahatma Gandhi. The toy train, Van Rani, is another popular attraction here, especially among kids. You can also visit the 2000-years-old Kanheri Caves to capture the Buddha relics. The undisturbed natural trails and the Jain Temple in the forest are also sure to make your visit a memorable one.)", "Adults – ₹53 per person, Children (Between 5 to 12 years of age) – ₹28 per person, Children (Below 5 years) – free, (Additional charges for Kanheri Cave visit, safari, boat ride, and toy train ride"),

  AppBanner(2, "Hanging Gardens", "Simla Nagar, Malabar Hill", " 05:00 am to 09:00 pm; every day", "hanginggardens.jpg", "Every relationship deserves a break from monotonous daily routines. Take your significant other to this amazing Hanging Garden and unwind and slacken yourself amidst the flower beds, spectacular water fountains, and lush green animal shaped hedges. Don’t miss out to take a funny picture with your partner at the giant boot structure here, known as the “Old Women Shoes”.", "free"),

  AppBanner(3, "Chota Kashmir", "Aarey, Goregaon", "10:00 am to 06:00 pm; every day", "chottakashmir.jpg", "If you are in search of a peaceful yet serene place to cherish some intimate moments with your partner, Chota Kashmir should be the right spot while you are in Mumbai. It has a beautifully landscaped garden and a placid lake that tranquillizes your body and mind. Recline peacefully on the greens of the garden or go boating in the lake and get lost in love on this little piece of paradise. Either way, you are sure to find a new spark in your love life!", "Free"),

];

List<AppBanner> lakesList = [
  AppBanner(1, "Powai Lake", "Powai Valley, Powai", "24×7", "powailake.jpg", "The beautiful and artificial Powai Lake is 12m deep and spread over 6.6 km. IIT Bombay is situated to the lake’s east and adds extra sparkle to it. Nature enthusiasts flock to this lake for its pretty pink-purple Balsam bushes and the wide variety of birds that you can see here, including sunbirds, kingfishers, kites, bulbuls, herons, ducks, parakeets, storks and doves. Even crocodiles have been spotted here.", "Free"),

];

List<AppBanner> cavesList = [
  AppBanner(1, "Elephanta Caves", "Gharapuri Islands", "9:00 am to 5:30 pm; closed on Mondays", "elephantacaves.jpg", "Take a tour to this UNESCO World Heritage Site in Mumbai and get wonderstruck by the massive rock-cut caves that date back to several centuries. It has five caves dedicated to Hindu god Shiva and two caves depicting Buddhist architectures. To reach this place, you need to take a one-hour ferry ride from the Gateway of India, during which you can also enjoy the scenic beauty of Mumbai. Those who lack the spirit of a trekker can hop on the toy train that will take you on a tour of the caves right from the entry point. The restaurant and canteen run by MTDC can take care of your hunger pangs. If you are planning a one-day tour to the Elephanta Caves, this blog will give you more details.", "Citizens of India, Afghanistan, Bangladesh, Bhutan, Maldives, Myanmar, Nepal, Pakistan, Sri Lanka, & Thailand – ₹10 per person, Other foreign citizens – ₹250 per person, (Separate charges involved for videography, toy train ride, and ferry ride)"),

  AppBanner(2, "Mahakali Caves", "Sunder Nagar, Andheri", "09:00 am to 06:00 pm, Monday to Sunday", "mahakalicaves.jpg", "If you wish to go back in time and explore something truly interesting, this group of 19 hillside caves should feature on your places-to-see list. Carved out of black solid basalt between 1st century BCE and 6th century CE, these ancient caves housed Buddhist monks once. They are also known as Kondivite Caves and boast a Buddhist Stupa as well as Pali scriptures on many walls.", "INR 20 per head"),

  AppBanner(3, "Kanheri Caves", "SGNP, Borivali", "07:30 am to 05:00 pm, Tuesday to Monday", "kanhericaves.jpg", "Nestled in the forests of Sanjay Gandhi National Park, the 109 caves here were carved out of basalt rock, between 1st century CE and 10th century CE. Ancient carvings, sculptures, inscriptions and paintings make these caves one of the most popular places to visit in Mumbai. The Kanheri Caves were once home to Buddhist monks who studied and meditated here, and still feature channels that drained rainwater into the cisterns. The congregation hall with its massive stupa and stone pillars is of special interest.", "Indians – INR 15 per head, Foreigners – INR 200 per head"),

  AppBanner(4, "Mandapeshwar Caves", "Borivali", "24x7", "mandapeshwarcaves.jpg", "Situated near Borivali West in Mumbai, Mandapeshwar Caves are 8th Century rock-cut shrine which are dedicated to the Hindu God - Shiva. Initially the caves were Buddhist Viharas, some time later they were occupied by the Brahmans. Currently they are a popular tourist site.", "Free"),

];

List<AppBanner> spiritualPlacesList = [
  AppBanner(1, "Siddhivinayak Mandir", "Prabhadevi", "05:30 am to 10:00 pm; every day", "siddhivinayakmandir.jpg", "One of the most frequented temples in Mumbai, the Siddhivinayak Temple is dedicated to Lord Ganesh. Devotees from across India including famous personalities from Bollywood and sports throng the temple to seek the blessings of Siddhivinayak Ganapati. The auspicious idol of Lord Ganesha is carved out in a single black stone with the trunk bent towards right making it one-of-its-kind. You can plan a visit to this temple with your family for an enriched spiritual experience.", "N/A"),

  AppBanner(2, "Mahalakshmi Mandir", "Mahalakshmi", "06:00 am to 10:00 pm, Monday to Sunday", "mahalakshmimandir.jpg", "Built in 1831 by a Hindu merchant named Dhakji Dadaji, this beautiful temple attracts numerous devotees daily, and more so on Diwali and Navaratra. On these two occasions, Shri Mahalakshmi is believed to come alive and grant the wishes of her worshippers. The other two deities housed here are Shri Mahasaraswati and Shri Mahakali. The vernacular domestic architecture of the temple and its unique surroundings, dotted with sweet and flower shops, make Mahalakshmi Temple an integral part of Maharashtra tourism.", "N/A"),

  AppBanner(3, "Mumbadevi Mandir", "Bhuleshwar, Mumbadevi", "06:00 am to 09:00 pm", "mumbadevimandir.jpg", "It is an old temple of the city dedicated to Goddess Mumba. The importance of this temple can be understood by the fact that the city of Mumbai derives its name from Goddess Mumbadevi. It is one of the most popular tourist places in Mumbai which gets hundreds of followers visiting on daily basis. As a visitor, the main highlight for you will be the Aatis conducted in the temple vicinity and shopping in the nearby shops of the vicinity. But, the main feature of the Mumba Devi Shrine is the icon of Goddess Mumbadevi, decorated with a silver crown, a brilliant golden neckband along with a nose stud. The idol is set on a sacred place, festooned with marigold blooms.", "N/A"),

  AppBanner(4, "Iskon Temple", "Hare Krishna Land, Juhu", "08:00 am to 01:00 pm and 04:15 pm to 09:00 pm, Monday to Sunday", "iskontemple.jpg", "Also known as Sri Sri Radha Rasabihari ji Temple, it is close to Juhu Beach and boasts 4 acres of land area. The gorgeously carved temple draws Hindu devotees in droves and hosts festivals like Ratha Yatra, Janmashtami, Radhasthami, Makarsankranti, and Gaura Purnima with great pomp and show. Crafted with marble, the temple comes with a 7-storey guesthouse, an auditorium, and a restaurant to help devotees attend spiritual programs with ease. The ISKCON Temple is also an educational hub and its library houses an impressive collection of spiritual books. ", "N/A"),

  AppBanner(5, "Mount Mary's Basilica", "Mount Mary, Bandra", "6:00 am - 9:00 pm", "mountmarychurch.jpg", "The Basilica of Our Lady of the Mount, commonly called as the Mount Mary Church by the locals, is a Roman Catholic Church situated atop a hillock 262 feet above sea level and is one of the finest specimens of its kind. Located in the suburbs of the vibrant city of Mumbai, the church enjoys a stunning view of the joyfully bustling Arabian Sea as it beautifully reflects different shades of blue.", "N/A"),

  AppBanner(6, "Haji Ali Dargah", "Dargah Rd, Haji Ali", "05:30 am to 10:00 pm; every day", "hajialidargah.jpg", "How about taking a trip with your family to one of the most popular religious shrines in Mumbai, built right in the middle of the Arabian Sea? Yes, we are talking about Haji Ali Dargah that houses the tomb of Sayed Peer Haji Ali Shah Bukhari. This grand edifice is made of white marbles and exemplifies the Indo-Islamic style of architecture. A walk through the causeway that connects the Dargah to the Lala Rajput Rai Marg is the main attraction of this place. Feel the spirituality of this place with your dear ones while enjoying a panoramic view of the deep blue waters! I give the places Fab rank no.4 among all the best places to visit in Mumbai.", "N/A"),

];

List<AppBanner> historicalPlacesList = [
  AppBanner(1, "Gateway of India", "Apollo Bandar, Colaba", "24×7; every day", "gatewayofindia.jpg", "Gateway of India, the best place to visit in Mumbai, was built in 1924 by George Willet to honor the visit of King George V and Queen Mary to Mumbai. Visit this place in the early morning or late evening hours to enjoy the cool breeze of the sea with your family sans the crowd. Located next to the iconic Taj Mahal Palace and facing the vast Arabian Sea, the Gateway of India leaves you spellbound in every way possible. Take a ferry ride offered here to experience a stupendous view of this monument right from the sea and you can also visit other main attractions nearby. And the best part? You don’t have to spend a penny to enjoy the beauty of this iconic monument which is often called the Taj Mahal of Mumbai. And the city has many such places that you can enjoy free of cost.", "Free entry (Ferry rides are chargeable)"),

  AppBanner(2, "Chhatrapati Shivaji Maharaj Terminus", "CSMT Area, Bori Bunder", "Every day", "csmt.jpg", "Chatrapati Shivaji Maharaj Terminus (CSMT), or otherwise known as Victoria Terminus (VT) is another UNESCO World Heritage Site situated right in the heart of Mumbai. Built in the year 1888, during the British colonial period, this edifice exemplifies the Victorian-Gothic style of architecture. While you are here, don’t forget to take a photograph with your family and kids. And guess what, the magnificent CST is the most photographed building in India after Taj Mahal! And once you are done with sightseeing, don’t forget to treat yourself and your dear ones to some lip-smacking food. Whether you are looking for budget restaurants, fine diners or buffet places, Mumbai has it all.", "N/A"),

  AppBanner(3, "Taj Mahal Palace", "Apollo Bandar, Colaba", "Check-ins: 02:00 pm onwards I Check-outs: Till 00:00 noon", "tajmahalpalace.jpg", "If you want to witness the luxuriousness of the cosmopolitan city, step in at the Taj Mahal Palace. Opened in 1903, this elegant edifice symbolizes as the city’s first harbor landmark. Every single corner of this palace exhibits nostalgic elegance and a personal taste of its own historical significance equipped with all modern amenities. Ballroom, itself is spacious to accommodate around 450+ guests at a time and can be reserved for both personal or professional events or celebrations. 9 iconic bars and restaurants raises its standard amongst the luxurious hotels nestling within the national frontiers.", "There are no entry charges here. However, if you are availing a room for your stay here, you need to spend around 30,000 INR per day."),

  AppBanner(3, "Rajabai Clock Tower", "Mantralaya, Nariman Point", "09:00 am to 10:45 pm; every day", "rajabaiclocktower.jpg", "South Mumbai’s famous clock tower, Rajabai Clock Tower stands erect in the close vicinity of the Mumbai High Court. The tower received its exquisite beauty through the imagination of Sir Gilbert Scott and is magically embellished with ancient figures and features. Here, the artist introduced a blend of both Venetian and Gothic architectural styles. Stained glass windows and a big clock right on its forehead completes its allure.This clock is known to play a melodious tune at predefined time intervals and is quite visible from a distance. It remained as the tallest edifice of the town until the next colossal structure marked its prominence.", "Free."),

];

List<AppBanner> museumsList = [
  AppBanner(1, "Bhau Daji Lad Museum", "Rani Baug, Byculla", "10:00 am to 05:30 pm", "bdlm.jpg", "Enter the immaculately restored heritage structure in Byculla, and you'll be blown away by the ornate ceiling, Corinthian columns, patterned-tiled floors and twinkling chandeliers. Once you manage to look away from the structure itself, you'll notice that it houses a host of other treasures. See 19th-century paintings by well-known artists from the J.J School of Art; study maps and photographs that showcase life in Mumbai in the 18th century; admire paintings on ivory from the 20th century; glimpse pottery over the ages and see a host of other artefacts that shed light on the art scene in Mumbai, over the years. This was formerly known as the Victoria and Albert Museum.", "Adult, 13 and above – Rs. 10/-, Child, 6 to 12 years – Rs. 5/-, Infant, 5 and below - Free"),

  AppBanner(2, "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", "Kala Ghoda, Fort", "10:15 am to 06:00 pm, Monday to Sunday", "csmvs.jpg", "Boasting a grand Indo-Saracenic architectural style, Chhatrapati Shivaji Maharaj Vastu Sangrahalaya is one of the famous places in Mumbai that demand your attention as a centre of entertainment and learning. Since the museum was built to commemorate the India visit of George V’s, the then Prince of Wales, it was initially named as the Prince of Wales Museum. Home to about 50,000 artefacts, this beautiful museum has received the 2010 UNESCO Asia – Pacific Heritage Award and is a must-visit if you are keen to know about our country’s heritage.", "Different packages are available for Indian adults, foreign adults, Indian senior citizens, children (5-12 years), students, defence personnel and group Indian visitors (15 and more). The range is from INR 60 to INR 700. INR 100 is charged for photography without the use of a tripod. You can visit the website for more details."),

  AppBanner(3, "CSMT Heritage Gllery", "CSMT Area, Fort", "03:00 pm to 05:00 pm, Monday to Friday", "railmuseum.jpg", "CSMT Railway Heritage Museum is a famous transportation which was Established in 2012. Chhatrapati Shivaji Terminus railway station is listed as UNESCO World Heritage Site since 2004. It was first railway station of the India which was established in 1888 by The British ruling Government. This railway station old name was Victoria Terminus which renamed in 1996 as Chhatrapati Shivaji Terminus.", "Students with valid ID: ₹100, All others: ₹200"),

  AppBanner(4, "RBI Monetary Museum", "Horniman Circle, Fort", "10:45 am to 05:15 pm, Tuesday to Sunday", "rbimuseum.jpg", "Did you know that India once minted coins that honoured a Greek Emperor? Learn about this and more at the Monetary Museum, aptly located within the Reserve Bank of India's building at Fort. Here, money talks and tells quite a story: you'll be taken through the history of Indian currency (from barter to coins and notes), you'll glimpse rare coins that bear emblems of Kings, religious imagery and even calligraphy.", "₹10 per person"),

  AppBanner(5, "BEST Transport Museum", "Anik Bus Depot, Sion", "Wednesday to Sunday – 9 am to 5 pm", "bestmuseum.jpg", "You cannot miss the bright red buses that ply the roads of Mumbai, covering every part of the city. Hop on for an enjoyable ride and get off at the Anik bus depot, off Wadala. Here, you'll learn everything there is to know about the public transport system and how it evolved over the years. See old bus tickets, black-and-white photographs of vintage buses, maps of routes, miniature buses, displays of badges worn by bus conductors and other memorabilia.", "Free"),

];

List<AppBanner> fortsList = [
  AppBanner(1, "Worli Fort", "Koliwada, Worli", "05:00 am - 07:00 pm", "worlifort.jpg", "Located in the Worli neighborhood of Mumbai, Worli Fort is an ancient defence fort that was built in around 1675. It is often mistaken to have been constructed by the Portuguese. But in reality, it was built by the British as a defence fort as their strategy to lookout for enemy ships and pirates. Overlooking the Mahim Bay, the fort offers some of the best views in the city and is visited by locals and tourists alike. In addition to that, the monument has a built-in well, a temple and ample viewpoints overlooking the vast sea.", "Free"),

  AppBanner(2, "Bandra Fort", "Bandstand Rd, Bandra", " 06:00 am - 06:30 pm", "bandrafort.jpg", "Also known as Castella de Aguada, Bandra Fort is an ancient Portuguese Fort that is situated in Land’s End in the Bandra neighborhood of Mumbai. The fort lies several feet high from the average sea level, at a height of 24 m. Besides being a major tourist spot in the region, the fort has also been featured in several Bollywood films like Dil Chahta Hai and Buddha Mil Gaya. It is also frequented by couples and love birds who come here for photo and video shoots, pre wedding shoots etc. Besides being an important historical site and a tourist attraction, Bandra Fort offers mesmerizing views of the sea. It is also known for its very stunning sunset views. In addition to that, the fort also has a staircased park that is visited by health freaks and fitness enthusiasts who come here to exercise and take routine walks. It is considered the most perfect place to meditate and relax.", "Free"),

  AppBanner(3, "Sewri Fort", "MPT, Sewri", "24x7", "sewrifort.jpg", "Built by the British in 1680 to serve as a watchtower, the Sewri Fort holds historic importance in the trading world of British-India. Overlooking the Mumbai harbor, the fort was primarily built for defense with high border walls and an inner ring for additional protection. The fort sits pretty on top of a 60-meter cliff, landlocked from three sides with the main entrance being a stone doorway, leading into a courtyard. The Archaeology department of Maharashtra is making efforts to revive the fort to ts od glory and also develop a museum in its premises.", "Free"),

  AppBanner(4, "Sion Fort", "Sion Circle, Sion", "6:00 am to 12:00 pm and 4:00 pm to 8:30 pm", "sionfort.jpg", "Sion Fort was constructed by the Governor of Bombay, General Gerald Aungier in the interest of offering a passage from Bombay to the neighbouring island of Salsette. It held prime importance to the British as Salsette was in the hands of the Marathas. Currently, the gap between Salsette and the fort has been taken up by commercial Eastern Express Highway. The Archeological Society of India maintains this piece of heritage. The Fort has disintegrated and does not stand in its original beauty and structure. It is quite evident when you contrast it with a picture captured by James Wales in 1791-92 to its current outlook.", "Free"),

  AppBanner(5, "Mahim Fort", "Koliwada, Mahim", "24x7", "mahimfort.jpg", "Built by the then Governor of Bombay - Gerald Aungier in 1669 to strengthen the defense of British-ruled Bombay, the Mahim fort was a place of strategic importance. It attracted many Gujarati Traders and Parsi Shipbuilders making the fort and the city more populous. It looks over Worli to the South, Bandra to the North and Mahim to the East. The fort is currently in a state of disrepair due to tidal erosion and administrative negligence.", "Free"),

  AppBanner(6, "Fort George", "CSMT Area, Indira Docks", "24x7", "fortgeorge.jpg", "Currently located in the neighbourhood of the Chhatrapati Shivaji Terminus (CST), Fort George was an extension of the fortified walls of then Bombay, in 1769. The fort was built near the hill where Fort Dongri is present. It was a mile (1.6 kilometres) long and about one-third of a mile (500 meters) wide. The fort was demolished in 1862 and now very little of the fort’s remnants are leftover in the present-day Fort area.", "Free"),

];

List<AppBanner> kidsAreaList = [
  AppBanner(1, "Veermata Jijabai Bhosale Zoo", "Mazgaon, Byculla", "09:30 am to 05:30 pm, closed on Wednesdays", "mumbaizoo.jpg", "Kids love zoos, period! While you are in Mumbai, you can have a great day out with your little ones at Veermata Jijabai Bhosale Zoo (or The Mumbai Zoo) that houses many wild animals like elephants, lion, tiger, monkeys, crocodiles, etc. The aviary includes some colorful birds and some rare ones like albino crows and flamingos. Sprawling over an area of 48 acres, one of the prominent attractions of the zoo is its penguin enclosure, which is kept in the perfect environment and temperature.", "Family of four – ₹100 and ₹25 for each extra child, Couples – ₹100, Students (Private schools) – ₹15 per person"),

  AppBanner(2, "Nehru Centre", "Dr Annie Besant Rd, Worli", "11:00 am to 05:00 pm; closed on Mondays", "nehrucentre.jpg", "Built in the memory of Pandit Jawaharlal Nehru, this center propagates his teachings and ideas through educational and cultural programs. It consists of a spectacular dome-shaped planetarium that creates curiosity about astronomy and science in young kids. You can stargaze with your little ones at the sky theater for a memorable time. Make your kids stand at the cubicle that calculates their weight in each of the nine planets of the solar system. Other attractions here, such as the miniature galaxy with Sun at the center, Moon’s surface, a view of Earth from Moon, art gallery, library, etc. will surely get your kids charged up with energy and intuitiveness.", "₹100 per person (4 years and above)"),

  AppBanner(3, "Taraporewala Aquarium", "Marine Drive, Girgaon", "10:00 am to 08:00 pm; closed on Mondays", "taraporewalaaquarium.jpg", "Touted as India’s oldest aquarium, this place houses a variety of marine and freshwater fishes including coral fishes from the Lakshadweep Islands. It also has an Oceanarium that gives you the feel of walking under the sea with exotic fishes floating above you. Well, there is more. Your kids can touch some of the aquatic fishes and animals without harming them at the Touch Pool. You can also enjoy a whale of a time at the fish spa along with your little ones. This aquarium is a perfect blend of education and entertainment, making it an ideal place to visit with kids.", "Adults – ₹60 per person, Children (Below 12 years) – ₹30 per person, Govt. Employees – ₹30 per person, (Separate charges for photography and videography)"),

  AppBanner(4, "Kidzania", "R City Mall, Ghatkopar", "10:00 am to 08:00 pm; Tuesday to Friday, 10:00 am to 03:00 pm and 04:00 pm to 09:00 pm; Saturday, Sunday and Public Holidays, Closed on Mondays", "kidzania.jpg", "Kidzania is an indoor amusement park made exclusively for kids with a unique concept of role-playing in a real city-like environment. Here, kids are required to perform a ‘job’ as a part of their role-playing. After successful completion of the job, they get paid in the form of kidzo money as an encouragement. You can see them brimming with joy as they make their own money for the first job in their life. Parents can relax at the lounge, from where they can monitor their kids on the TV screen. With such interactive edutainment activities, Kidzania should be your ideal destination for a fun-filled day with your tiny tots.", "Different packages for kids, adults, and senior citizens, ranging from ₹300 to ₹1500. Check the website for more details."),

];

List<AppBanner> bollywoodSpotsList = [
  AppBanner(1, "Dadasaheb Phalke Chitranagari", "Aarey Colony, Goregaon", "10:00 am to 05:00 pm; every day", "filmcity.jpg", "Sprawling over approximately 100,000 sq. ft. area, the Dadasaheb Phalke Chitranagari also known as Mumbai Film City is a world of wonders where you can see theaters, gardens, lakes, recording rooms, and grounds that are leased out for Bollywood film shootings. Take a bus tour of the film city with your friends and see the familiar sets of popular sitcoms and movies. If you and your pals are die-hard fans of Bollywood, this film city is something you shouldn’t miss out on.", "Tours starting at ₹599"),

  AppBanner(2, "Prithvi Theatre", "Juhu Church Rd, Juhu", "01:00 pm to 09:00 pm, Tuesday to Sunday", "prithvitheatre.jpg", "If you are a connoisseur of performing and fine arts and things that make you think, a visit to the Prithvi Theatre is a must. Built in the memory of Prithviraj Kapoor, this theatre conducts meaningful live performances in various languages and even online workshops. One of the top places to visit in Mumbai, it hosts many festivals too, and has a bookshop and café to cater to your mind and gastronomic juices. Since 1978, this theatre has always been about embracing new ideas, respecting each other, and evolving as human beings.", "Show ticket prices can range from INR 125 to INR 400. You can visit the website for more details."),

  AppBanner(3, "Red Carpet Wax Museum", "Amrut Nagar, Ghatkopar", "09:45 am to 09:30 pm; every day", "redcarpetwaxmuseum.jpg", "Ever imagined standing next to Barack Obama, striking a pose with Michael Jackson or taking a selfie with Harry Potter? Yes, you read it right. Come to the city of dreams and fulfil this dream at the Red Carpet Wax Museum. It exhibits lifelike wax figures of prominent icons from various fields including science, politics, sports and world cinema. So, take selfies with your favorite icon, post it on social media, and make your friends jealous.", "Weekdays – ₹250 per person, Weekends – ₹350 per person, (Check their website for details on combo offers)"),

];

List<AppBanner> themeParksList = [
  AppBanner(1, "Essel World", "Gorai Island, Borivali", "10:00 am to 06:30 pm, Monday to Sunday", "esselworld.jpg", "Looking for adventure and thrill in the heart of bustling Mumbai? You can head to EsselWorld to have fun with the whole family. A wide array of vibrant and exciting rides await at this famous amusement park, to give you the adrenaline rush you want while shooting up in the air or plunging into cold water. Roller coasters, kid-friendly rides, challenges, and a cheerful playground make EsselWorld the complete package. It is a happening destination for wedding photography and events too.", "Multiple packages are available for both children and adults, including Basic, Silver, Fast Track + Silver, Combine and Annual Pass – Passport Next. The price ranges from INR 290 to INR 1640. You can visit their website for more details."),

  AppBanner(2, "Smaaash", "Kamala Mills, Lower Parel", "11:00 am to 12:30 am", "smaaash.jpg", "As the name suggests, Smaaash offers you a beautiful blend of sports, music and fine dining experience. Spread across an area of around 40,000 sq.ft. This theme park in Mumbai has been designed with the motive of pioneering into Sports Stimulation Technology in India. Well, the most notable thing about this amusement park in Mumbai is its wide range of technically advanced and innovative sports activities. Unravel the unparalleled experience of participating in games like Twilight Bowling, X2 Motor Racing, Goalie Guacamole, and Hoopla Zone. This stunning fusion of virtual and real sports makes Smaash one of the most unique amusement parks in Mumbai.", "₹675 per person"),

  AppBanner(3, "Snow World", "Phoenix Market City, Kurla", "11:00 am to 10:00 pm; every day", "snowworld.jpg", "Now, you can experience -10° C temperature in Mumbai with some frolicsome activities at Snow world, another great place to have serious fun with your friends. Feel the natural snowfall, slide through the ice in a rubber tube, play snowball wars with your buddies, run down the ice slope screaming with joy, go ice skating and learn some snowboarding while you are in this really ‘coool’ place. Enthralling right?", "₹575 per person"),

  AppBanner(4, "Water Kingdom", "Gorai Island, Borivali", "Monday to Thursday – 11:00 am to 06:00 pm, Weekends and Holidays – 11:00 am to 07:00 pm", "waterkingdom.jpg", "Among Asia’s largest theme water parks, Water Kingdom Mumbai also has the largest wave pool in the world. With a huge range of slides for all age groups, play pools, and amazing photo-ops, this is your go-to place to unwind and rejuvenate yourself. If one day seems less, then book a hotel nearby and stay over to make the most out of this thrilling water park.", "Adult – ₹ 1050, Children – ₹ 696"),

];

List<AppBanner> otherPlacesList = [
  AppBanner(1, "Marine Drive", "Marine Drive, Kalbadevi", "24 x 7", "marinedrive.jpg", "Walk hand in hand with your lover along the walkway at Marine Drive witnessing the sunset hues reflecting on the vast Arabian Sea. It is an ideal place to relax and spend some romantic moments on a beautiful evening. This is also one of the popular places to visit in Mumbai at night. Don’t forget to satiate your hunger with some delicious street food available here. ", "Free"),

  AppBanner(2, "Bandra Worli Sea Link", "Koliwada, Worli", "24×7", "sealink.jpg", "A magnificent example of modern architecture, the Bandra-Worli Sea Link is a cable-stayed bridge that features viaducts made of pre-stressed concrete and steel on either side. It can support a total of 8 lanes of traffic (to and fro) and is a staggering 5.6 km in length. This bridge is not only worthy of photography, but also makes travelling between Bandra and Worli super simple by spanning across Mahim Bay.", "Toll for Car – INR 70, Light Commercial Vehicle – INR 110, Heavy Vehicle – INR 145 "),

  AppBanner(3, "Global Vipassana Pagoda", "Gorai, Borivali", "09:00 am to 07:00 pm (entry allowed till 06:30 pm), Monday to Sunday (ID proof required)", "globalpagoda.jpg", "Finding peace amidst Mumbai’s hustle and bustle is possible if you pay a visit to this picturesque pagoda. Designed to accommodate 8000 Vipassana meditators, the pagoda’s architectural style is Burmese. While the pagoda has 3 sub-domes, the largest and first dome holds Buddha’s bone relics. Different courses are offered to new and old students who wish to embrace Buddha’s teachings, practise gratitude and shed mortal bindings.", "Free"),

  AppBanner(4, "Bandra Bandstand", "Mount Mary, Bandra", "24x7", "bandrabandstand.jpg", "Bandra Bandstand or Bandstand Promenade is the popular promenade in the queen suburbs of Bandra in Mumbai. It boasts of a joggers’ strip and a park making it quite a popular hangout spot. Dotted with food junctions and sprinkled with hawkers selling street snacks, the promenade is replete with swarms of people at all points of the day. Besides presenting an enthralling picture of the adjacent sea and the mesmerising skyline, Bandstand also boasts of being Shahrukh Khan’s residential place, which is a major pull for the tourists.", "Free"),

  AppBanner(5, "Jehangir Art Gallery", "Kala Ghoda, Fort", "11:00 am to 07:00 pm, Monday to Sunday", "jag.jpg", "Built in 1952 and backed by Sir Cowasji Jehangir’s funding, this art gallery is a popular space for many important exhibitions by photographers, painters, sculptors, craftsmen, weavers and alike. It was established with the aim of promoting contemporary Indian art and forging a bond between aspiring artists and art patrons. S. H. Raza and M. F. Hussain are among the noted artists who have had exhibitions here.", "Free"),

];